const byId = <T extends HTMLElement>(id: string): T => document.getElementById(id) as T;
const byQuery = <T extends Element>(selector: string): T => document.querySelector(selector) as T;

export const dom = {
  appShell: byQuery<HTMLElement>(".app"),
  welcome: byId<HTMLElement>("welcome"),
  lobby: byId<HTMLElement>("lobby"),
  modeMultiplayer: byId<HTMLButtonElement>("modeMultiplayer"),
  backToWelcome: byId<HTMLButtonElement>("backToWelcome"),
  showCreate: byId<HTMLButtonElement>("showCreate"),
  showJoin: byId<HTMLButtonElement>("showJoin"),
  createPanel: byId<HTMLElement>("createPanel"),
  joinPanel: byId<HTMLElement>("joinPanel"),
  waitingPanel: byId<HTMLElement>("waitingPanel"),
  waitingSettings: byId<HTMLElement>("waitingSettings"),
  waitingPlayers: byId<HTMLElement>("waitingPlayers"),
  waitingNameInput: byId<HTMLInputElement>("waitingNameInput"),
  waitingNameSave: byId<HTMLButtonElement>("waitingNameSave"),
  waitingStartBtn: byId<HTMLButtonElement>("waitingStartBtn"),
  modeInput: byId<HTMLSelectElement>("modeInput"),
  languageInput: byId<HTMLSelectElement>("languageInput"),
  wordCountInput: byId<HTMLInputElement>("wordCountInput"),
  lengthModeInput: byId<HTMLSelectElement>("lengthModeInput"),
  fixedLengthWrap: byId<HTMLElement>("fixedLengthWrap"),
  fixedLengthInput: byId<HTMLInputElement>("fixedLengthInput"),
  rangeWrap: byId<HTMLElement>("rangeWrap"),
  minLengthInput: byId<HTMLInputElement>("minLengthInput"),
  maxLengthInput: byId<HTMLInputElement>("maxLengthInput"),
  createBtn: byId<HTMLButtonElement>("createBtn"),
  joinBtn: byId<HTMLButtonElement>("joinBtn"),
  codeInput: byId<HTMLInputElement>("codeInput"),
  main: byQuery<HTMLElement>(".main"),
  grid: byId<HTMLElement>("grid"),
  historyPanel: byId<HTMLElement>("historyPanel"),
  historyList: byId<HTMLElement>("historyList"),
  playersList: byId<HTMLElement>("playersList"),
  keyboard: byId<HTMLElement>("keyboard"),
  message: byId<HTMLElement>("message"),
  wordStat: byId<HTMLElement>("wordStat"),
  scoreStat: byId<HTMLElement>("scoreStat"),
  roomPill: byId<HTMLElement>("roomPill"),
  nameEditWrap: byQuery<HTMLElement>(".name-edit"),
  homeBtn: byId<HTMLButtonElement>("homeBtn"),
  nameEdit: byId<HTMLInputElement>("nameEdit"),
  nameSave: byId<HTMLButtonElement>("nameSave"),
  startBtn: byId<HTMLButtonElement>("startBtn"),
  viewPodiumBtn: byId<HTMLButtonElement>("viewPodiumBtn"),
  podiumOverlay: byId<HTMLElement>("podiumOverlay"),
  podiumTop: byId<HTMLElement>("podiumTop"),
  podiumLeft: byId<HTMLElement>("podiumLeft"),
  podiumRight: byId<HTMLElement>("podiumRight"),
  podiumRest: byId<HTMLElement>("podiumRest"),
  podiumWatch: byId<HTMLButtonElement>("podiumWatch"),
  podiumReplay: byId<HTMLButtonElement>("podiumReplay"),
  podiumClose: byId<HTMLButtonElement>("podiumClose")
};
